[ci] Update CI jobs to build and check webui

diff --git a/web-src/Makefile.am b/web-src/Makefile.am
--- a/web-src/Makefile.am
+++ b/web-src/Makefile.am
@@ -191,8 +191,24 @@ web-serve: node_modules
 web-update:
 	$(if $(NPM),$(NPM) update)
 
+web-check:
+	@echo "Verifying that all source files in 'src' and 'public' are listed in WEB_FILES ..."
+	@unexpected_files=0; \
+	for file in $$(find public src -type f); do \
+		if ! echo " $(WEB_FILES) " | grep -q " $$file "; then \
+			echo "Unknown web interface source file found: $$file"; \
+			unexpected_files=1; \
+		fi; \
+	done; \
+	if [ $$unexpected_files -eq 0 ]; then \
+		echo "All source files listed in WEB_FILES."; \
+	else \
+		echo "FAILURE: Unknown web interface source files found, please add them to WEB_FILES."; \
+		exit 1; \
+	fi
+
 web-lint: node_modules
-	$(if $(NPM),$(NPM) run lint)
+	$(if $(NPM),$(NPM) run lint --no-fix)
 
 web-format: node_modules
 	$(if $(NPM),$(NPM) run format)
